Lambda-School-Labs/Labs8-TeamComms

package.json, yarn.lock
Please include a summary of the change and a link to which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.
=> added dependencies, redux, react-redux, redux-saga, eslint, react-router-dom,  --dev prettier, --dev eslint-plugin-prettier

README.md
Please include a summary of the change and a link to which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.
N/A, Documentation update only.
=> readme updated, most sections in progress

package.json, yarn.lock
- removed eslint 5.8.0 dependency from front-end package.json (caused Netlify automated build to break)
Forked repo, removed the dependency, connected forked repo to netlify, checked automated build, now works.
Removed dependency from this repo, ran yarn build locally on this repo to make sure it worked.
=> updated package dependencies

src/App.js, src/index.js
Added React Router imports to index.js, wrapped App component, and added test route to app.js
Route tested manually at 'http://localhost:3000/landing'
=> add-react-router

package.json, src/actions/fetchAllMissionsAction.js, src/actions/index.js, src/actions/types.js, src/reducers/fetchAllMissionsReducer.js, src/reducers/index.js, yarn.lock
Added redux biolerplate, with separatation of files for team collaboration.  
Added axios dependancy.
Tested locally.  Further testing to follow after merge and pull.
=> redux boilerplated, axios dependency added

netlify.toml
Fixes react-router redirects
Tested with separate repo on netlify
=> hotfix-netlify-deploy

README.md
Added documentation for User API endpoints to the README.
https://trello.com/c/e57NZYFx
NA
=> User API Documention

src/components/Signup/index.js
Created the front end function to handle register.
https://trello.com/c/PkIsY6IH
Tested with postman and with the client.
=> Register User Function

src/App.js, src/components/ConvoList/convoList.css, src/components/ConvoList/dummyData.js, src/components/ConvoList/index.js, src/screens/ConvoList/index.js
Created the basic conversation list component and populated with dummy data till server/db is ready.
=> Conversation List Page

server/helpers/UserHelpers/userEdit.js, server/helpers/UserHelpers/userLogin.js, server/helpers/UserHelpers/userRegister.js, server/models/UserModel.js, server/routes/userRoutes.js, server/validation/generateToken.js, server/validation/tokenCheck.js
Made most user fields required. Added phone number format validation and email validation to check if unique. Added checks on user edit to make sure proper information was being sent to server. Added 'bearer' to front of token and changed token validation accordingly. Tokens no longer hold username, only user id. Changed comments to match new user route requests. Added some qol responses to front end when trying to hit end points that arent recieving proper requests. 
Tested with postman. Many times.
=> added email and phone number validation. login is done with email and pw

server/helpers/UserHelpers/userEdit.js, server/helpers/UserHelpers/userLogin.js, server/helpers/UserHelpers/userRegister.js, server/models/UserModel.js
Added displayName, familyName, givenName to schema. Changed endpoints accordingly.
Postman
=> changed user schema to add user names

src/actions/callLogIn.js, src/actions/callReg.js, src/history.js
Adds functionality to redirect from login or registration action call, after successfully logging in.
tested locally.
=> redirects from action call to conversations

package.json, src/App.js, src/Root.js, src/index.js, yarn.lock
Adds Redux-Persist dependency for persistent data across browser refresh. 
Removes unneeded dependencies:
redux-saga
connected-react-router
Updates Root component and routes for browser refresh.
browser refresh was causing loss of state. fixed.
tested with console logs, tested on local server.
=> Redux-persist

package.json, src/components/Header/index.js, src/components/Stripe/index.js, yarn.lock
Integrated Stripe API to the front end. This button opens a module to collect payment info and then returns a token. Use token with server to process payment.
*Still pending a test with the backend endpoint
=> Billing stripe integration

.gitignore, server/helpers/UserHelpers/userRegister.js, server/models/UserModel.js, server/package.json, server/routes/apiRoutes.js, server/routes/authRoutes.js, server/routes/userRoutes.js, server/server.js, server/services/passport-setup.js, server/validation/generateToken.js, server/yarn.lock
Added OAuth. Added jwt-middleware. 
postman
=> Oauth implement

server/routes/authRoutes.js, yarn.lock
Added token in url to dashboard redirect
=> Server redirect

src/actions/callGoogleLogIn.js, src/screens/ConvoList/index.js
removed 1 argument from callGoogleLogin function
=> removed 1 argument from callGoogleLogin function

server/package.json, server/routes/apiRoutes.js, server/routes/stripeRoutes.js, server/yarn.lock, src/components/Stripe/index.js
Created backend endpoint on server to receive Stripe token and send to Stripe API to complete transaction.
=> Stripe backend integration

server/helpers/UserHelpers/UserModules.js, server/helpers/UserHelpers/_UserModules.js, server/helpers/UserHelpers/userEdit.js, server/helpers/UserHelpers/userFindByName.js, server/helpers/UserHelpers/userRetrieve.js, server/models/UserModel.js, server/routes/userRoutes.js, server/validation/generateToken.js
Added a endpoint to retrieve information by passing user through passport and verifying token, then sending user data back to client.
Postman
=> added retrieve and findbyname endpoint

server/routes/authRoutes.js
Fixed type in redirect url!!!!
=> Type oauth fix

src/App.js, src/components/UserPreferences/index.js
Created the base user preferences component with minor styling.
=> User preferences

src/App.js, src/components/Convo/index.js, src/components/ConvoList/index.js, src/index.js
added basic conversation detail component
=> Basic convo detail component

server/routes/_apiRoutes.js, server/server.js, server/services/socketio.js, src/components/socketClient/css.css, src/components/socketClient/index.js, yarn.lock
Socketio now runs on the same port as the server. Functionality extracted out of server.js
Tested by just running in a mock  chat window
=> socketio runs on same port

server/helpers/ConvoHelpers/_ConvoModules.js, server/helpers/ConvoHelpers/convoCreate.js, server/models/ConvoModel.js, server/models/UserModel.js, server/routes/_apiRoutes.js, server/routes/convoRoutes.js
=> convo-server-model

server/helpers/ConvoHelpers/_ConvoModules.js, server/helpers/ConvoHelpers/convoRetrieve.js, server/routes/convoRoutes.js, src/components/socketClient/index.js
=> convo retrieve complete

package.json, server/services/socketio.js, src/components/Meeting/index.js, src/index.js, yarn.lock
updated Meeting component with namespace and rooms based on meeting ids, updates server to parse room/meeting ids
When a meeting was created previously, all meetings were being sent the same messages, now they are specific to the meeting
tested locally
=> Sockets-fix

server/helpers/ConvoHelpers/convoAdd.js, server/package.json, server/yarn.lock
Specified engines in package.json and added an enpoint for adding users to conversations
Postman
=> heroku fix and convo add

src/components/CreateMeeting/index.js, src/components/UserPreferences/index.js
Refactored the User Preferences and the Create Meeting components with PrimeReact components.
=> PrimeReact preferences create

server/helpers/ConvoHelpers/convoCreate.js, server/models/ConvoModel.js, server/package.json, server/yarn.lock
added moment package to server, parsing input from from post to date obj, added error handling
=> adding-moment-to-server

server/helpers/UserHelpers/_UserModules.js, server/helpers/UserHelpers/userAll.js, server/routes/userRoutes.js
Created an endpoint to return all users
=> Created endpoint to get all users

server/services/socketio.js, src/components/Common/index.js, src/components/Meeting/index.js
adds websocket questions and websocket attendees based on meeting. currently data is being saved on the server as temporary arrays, still need to setup database calls.
Tested Locally
=> meeting-attendees-questions

server/helpers/UserHelpers/userAll.js, server/routes/userRoutes.js
Added filter to query to remove id. Added authentication to endpoint
postman
=> userall tweak and added authenticate to endpoint

src/components/Login/index.js, src/components/Register/index.js
Refactored Login and Register components to use PrimeReact components.
=> PrimeReact Login Register

server/helpers/ConvoHelpers/convoCreate.js, server/models/ConvoModel.js, server/routes/_apiRoutes.js
=> add-question-to-db

server/helpers/UserHelpers/userAll.js, src/actions/callCreate.js, src/components/CreateMeeting/index.js
Fixed bugs where create meeting form and attendee IDs was not working.
=> Create Meeting Issues

src/components/Common/index.js, src/components/Header/index.js, src/components/Login/index.js, src/components/Register/index.js
updates css with responsive mobile menu, updates login for under 500px screen to full width
local server testing
=> css-responsive-fixes

src/components/Meeting/index.js, src/components/MeetingList/index.js, src/index.js
requires reverting state using redux dev tool
=> kill-dummy-data

server/models/LiveMeetingModel.js, server/services/socketio.js, src/components/Meeting/index.js
Connected sockets to db. Questions and notes are maintained. Notes are a work in progress. New model was created to handle the live meeting.
On local machine
=> sockets connected to database, still need to save notes to db

server/helpers/ConvoHelpers/convoCreate.js, server/models/ConvoModel.js, server/models/LiveMeetingModel.js, server/services/socketio.js
Socketio working with database. Attendees and questions persist. Few bugs still 
localhost, postman
=> socketio functioning, few bugs but working

src/components/Meeting/css.css, src/components/Meeting/index.js
updates meeting css and adds responsive attendee list
tested locally
=> responsive-detail

server/helpers/ConvoHelpers/_ConvoModules.js, server/helpers/ConvoHelpers/convoCreate.js, server/helpers/ConvoHelpers/convoFindById.js, server/models/ConvoModel.js, server/routes/convoRoutes.js, src/components/CreateMeeting/index.js
Added an endpoint to find convo by id. api/meeting/findbyid/:id. When hitting the endpoint with an id from a conversation that has been created, it finds the conversation in the database and returns the conversation in whole, including populating the "invitees" array with actual user objects. Also found bugs in the create convo component as well as the convo model.
Fixes invitees not being properly added in component. This was happening because user id's were being added to body of createconvo endpoint by user.id. Id's are saved automatically as _id. I also removed a field in the conversation model under invitees. User Id's are now added as strings into the invitees array instead of objects.
Postman and locally.
=> Convofindbyid

server/helpers/ConvoHelpers/_ConvoModules.js, server/helpers/ConvoHelpers/convoUpdate.js, server/routes/_apiRoutes.js, server/routes/convoRoutes.js, src/actions/callUpdateMeeting.js, src/components/UpdateMeeting/index.js
=> Update meeting endpoint

server/services/socketio.js, src/components/Meeting/index.js
Fixed compatibility with sockets
locally
=> sockets working a bit smoother. few more kinks though

server/server.js
=> Cors config

server/server.js
=> another try

server/server.js
=> server.use

server/server.js
=> server.use headers

server/helpers/ConvoHelpers/convoUpdate.js, src/components/UpdateMeeting/index.js
Added checks for empty arrays in the meeting update
=> added checks for empty arrays in invitees

server/server.js
=> added multiple origins

src/components/CreateMeeting/index.js, src/components/Login/index.js, src/components/Register/index.js, src/components/UpdateMeeting/index.js, src/components/UserPreferences/index.js
Fixed spacing on forms. On all forms the placeholder hovers above when field is populated. It cause crowding so I went through and fixed spacing on all forms.
=> Fixing spacing on forms

server/services/socketio.js, src/components/Meeting/index.js
Added some polish to sockets. Db save's are more reliant.
Duplicate attendees. Database errors from concurrent saves
Localhost
=> Socket polishv3

server/helpers/ConvoHelpers/convoCreate.js
Added check for zoom id in convo create
Creation wasn't happening if zoom wasn't added
locally
=> added check for zoom meeting

src/components/Header/index.js, src/components/UserPreferences/index.js, src/reducers/index.js
Added a button to header to go to preferences page. Also fixed the layout and redux for that component.
=> Preference button and layout

server/helpers/ConvoHelpers/convoUpdate.js, src/components/UserPreferences/index.js
Fixed display bugs around the different components.
=> Display bug fixes

src/actions/callGoogleLogIn.js, src/components/MeetingList/index.js, src/screens/MeetingList/index.js
Added fix for google oauth not recieving list of meetings.
Oauth not recieving meeting list
Locally
=> added fix for google oauth not recieving meeting list

src/components/Meeting/index.js
=> add zoom url to meeting component

server/helpers/ConvoHelpers/convoCreate.js, server/helpers/SendGrid/sendGrid.js, server/package.json
Added mutliple emails to be sent up from sendgrid and added Error checks to be caught from the sendgrid api
Locally
=> Multi email sendgrid

server/helpers/ConvoHelpers/_ConvoModules.js, server/helpers/ConvoHelpers/convoCreate.js, server/helpers/SendGrid/sendGrid.js, server/helpers/UserHelpers/userAll.js, server/helpers/UserHelpers/userEdit.js, server/helpers/UserHelpers/userLogin.js, server/helpers/UserHelpers/userRegister.js, server/package.json, server/server.js, server/services/sendGrid.js, server/services/socketio.js, server/validation/ErrorHandling/ServerError.js, server/validation/ErrorHandling/errorHandler.js, src/actions/callCreate.js
Fixed Socket issues. Added more robust error handling for server-to-client by creating error handling middleware and a ServerError class that can be thrown with the respective code and message. Only implemented on User routes so far. All new error handling code can be found in validation->Error. See the errorHandler function for proper codes to use(and feel free to add or tweak if necessary). 
***Moved sendgrid function to services***
Fixes sockets shutting down the server. I fixed the issue with the database save that was closing on finalize, and also the crash if the page is refreshed. 
This has been tested locally and with postman
=> Server tweaks

src/components/MeetingList/index.js
=> Added cursor pointer to big add button

src/App.js
Added a ternary statement to change the redirect depending if user is logged in or not.
Fixes #107 
=> logo ternary redirect

server/helpers/ConvoHelpers/convoDelete.js
changed git config to not ignore case
=> changed git config to not ignore case sensitive file rn

src/components/CreateMeeting/index.js, src/components/UpdateMeeting/index.js
Fixed layout issue of calendar modals and set validation to only allow today forward.
Fixes #111 #118 
=> fixing calendar on create and update

src/components/MeetingCard/index.js
Added a confirmation modal after user clicks trash can.
Fixes #113 
=> Delete confirmation modal

src/components/Chart/index.js, src/components/Common/index.js, src/components/Meeting/css.css, src/components/Meeting/index.js, src/components/Register/index.js
updates chart and attendee components, css
local
=> updates chart and attendee components, css

server/helpers/ConvoHelpers/convoDelete.js
Invitees now have deleted conversation removed from their meeting list. 
Postman
=> invitees meetings list are now updated when convo is deleted

src/components/Header/index.js, src/components/Stripe/index.js
Fixed the alignment issue with stripe button in menus
Fixes #112 
=> stripe alignment fix

src/components/MeetingList/index.js
Made the add icon teal when no meetings exist.
Fixes #139 
=> Teal add icon

server/services/socketio.js, src/components/Meeting/index.js
Changed finalize meeting to save. Saves the data to database so the meeting could be jumped in and out of
locally
=> Socket save

src/actions/callGoogleLogIn.js, src/actions/getMeetings.js, src/components/Register/index.js
fixes id conflict, removes history push on callGoogleLogin
locally
=> fixes id conflict

src/components/MeetingList/index.js
Fixed hover transition of large add button
=> Fixed hover transition

src/screens/MeetingList/index.js
fixed meeting list redirect
locally
=> fixed redirect meetinglist

src/components/CreateMeeting/createMeeting.css, src/components/CreateMeeting/index.js, src/components/Register/index.js
=> improvements

server/helpers/ConvoHelpers/convoCreate.js, server/helpers/ConvoHelpers/convoFindById.js, server/helpers/ConvoHelpers/convoRetrieve.js, server/helpers/ConvoHelpers/convoUpdate.js, server/services/sendGrid.js, src/actions/callUpdateMeeting.js, src/components/Meeting/index.js, src/components/UpdateMeeting/index.js
Added buffer for sockets. Fixed bug with convo findbyid where if id was invalid, it crashed the server. Added better error handling in endpoints. Changed the updatemeeting component so it redirected to the correct meeting on save and view
Fixed lag with the sockets, still not perfect.
Postman, locally
=> Notes buffer

README.md
Adds table of contents to readme file.
=> Readme-toc

src/App.js
Minor fix to createMeeting route.
=> fixed create route

src/components/Header/index.js
Fixed the layout of the mobile menu when not logged in.
=> mobile menu layout

src/App.js
=> fixes masthead css

README.md, src/screens/Landing/index.js
=> Fix masthead 

server/package.json, server/server.js, server/tests/convoCreate.spec.js, server/tests/userLogin.spec.js, server/tests/userRegister.spec.js
Added backend tests for login, register and convo create. Made server not listen to port when in test environment. 
I tested the tests with tests made by testing
=> Backend tests

server/routes/authRoutes.js
=> updated redirect link for google oauth
